### ISSUE TITLE
Swift code out of date

### ISSUE THREAD

**Issue by jewilhel** [FlexMonkey/UIScrollViewDemo#1]
Can this code base be updated to Swift 3.0? Would really help. I tried to do a conversion myself, but there are too many errors and I keep running into problems. Need your help please.  Thanks - Jason W.

**Comment by FlexMonkey** [comment]
Hi,

Unfortunately, the terms of my contract with my new employer prohibits me from working on this code at the moment. 

Sorry I can't help further at this time.

Simon
